import type { Arrangement, Category } from "./types";

// Estos datos de ejemplo se muestran cuando Sanity todavía NO está
// configurado, para que veas el sitio funcionando de inmediato.
// Cuando conectes tu proyecto de Sanity, se usan tus datos reales.

export const sampleCategories: Category[] = [
  { _id: "c1", name: "Ramos", slug: "ramos", order: 1 },
  { _id: "c2", name: "Cajas", slug: "cajas", order: 2 },
  { _id: "c3", name: "Eventos", slug: "eventos", order: 3 },
  { _id: "c4", name: "Plantas", slug: "plantas", order: 4 },
];

export const sampleArrangements: Arrangement[] = [
  {
    _id: "a1",
    name: "Ramo Primavera",
    slug: "ramo-primavera",
    price: 245,
    category: { name: "Ramos", slug: "ramos" },
    shortDescription:
      "Ramo cálido en tonos durazno, perfecto para alegrar cualquier día.",
    flowers: ["lilis", "alstroemeria", "hypericum", "craspedia"],
    isFeatured: true,
    isAvailable: true,
    order: 1,
  },
  {
    _id: "a2",
    name: "Campo Silvestre",
    slug: "campo-silvestre",
    price: 290,
    category: { name: "Ramos", slug: "ramos" },
    shortDescription:
      "Estilo natural y fresco, como recién cortado del jardín.",
    flowers: ["margaritas", "claveles", "gypsophila", "eucalipto"],
    isFeatured: true,
    isAvailable: true,
    order: 2,
  },
  {
    _id: "a3",
    name: "Blanco Sencillo",
    slug: "blanco-sencillo",
    price: 260,
    category: { name: "Ramos", slug: "ramos" },
    shortDescription: "Elegancia en blanco para los momentos importantes.",
    flowers: ["rosas blancas", "lisianthus", "follaje"],
    isFeatured: true,
    isAvailable: true,
    order: 3,
  },
  {
    _id: "a4",
    name: "Atardecer Durazno",
    slug: "atardecer-durazno",
    price: 320,
    category: { name: "Ramos", slug: "ramos" },
    shortDescription: "Tonos cálidos que recuerdan a una tarde de verano.",
    flowers: ["lilis durazno", "craspedia", "eucalipto"],
    isAvailable: true,
    order: 4,
  },
  {
    _id: "a5",
    name: "Caja Jardín",
    slug: "caja-jardin",
    price: 480,
    category: { name: "Cajas", slug: "cajas" },
    shortDescription: "Arreglo en caja con flores de temporada y follaje fino.",
    flowers: ["rosas", "hortensia", "follaje"],
    isFeatured: true,
    isAvailable: true,
    order: 5,
  },
  {
    _id: "a6",
    name: "Mini Detalle",
    slug: "mini-detalle",
    price: 190,
    category: { name: "Cajas", slug: "cajas" },
    shortDescription: "Pequeño y encantador, ideal para sorprender.",
    flowers: ["mini rosas", "gypsophila"],
    isAvailable: true,
    order: 6,
  },
  {
    _id: "a7",
    name: "Centro de Mesa Boda",
    slug: "centro-de-mesa-boda",
    price: 850,
    category: { name: "Eventos", slug: "eventos" },
    shortDescription: "Centro de mesa elegante para bodas y celebraciones.",
    flowers: ["rosas", "eucalipto", "velas"],
    isFeatured: true,
    isAvailable: true,
    order: 7,
  },
  {
    _id: "a8",
    name: "Suculenta en Maceta",
    slug: "suculenta-en-maceta",
    price: 150,
    category: { name: "Plantas", slug: "plantas" },
    shortDescription: "Una planta que dura, con un toque verde y minimalista.",
    flowers: ["suculenta", "piedra volcánica"],
    isAvailable: true,
    order: 8,
  },
  {
    _id: "a9",
    name: "Orquídea Phalaenopsis",
    slug: "orquidea-phalaenopsis",
    price: 420,
    category: { name: "Plantas", slug: "plantas" },
    shortDescription: "Belleza serena y duradera para regalar o decorar.",
    flowers: ["orquídea blanca"],
    isAvailable: true,
    order: 9,
  },
];
